// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::hdf5_writer::Hdf5Writer;

#[test]
fn checksum_matches_lookup3_empty_input() {
    let writer = Hdf5Writer::new();

    assert_eq!(writer.checksum(&[]), 0xdead_beef);
}

#[test]
fn write_undeclared_variable_is_missing_variable() {
    let mut writer = Hdf5Writer::new();
    assert!(matches!(
        writer.write_f32("Nope", &[1.0]),
        Err(crate::SofaError::MissingVariable(_))
    ));
    assert!(matches!(
        writer.write_scalar_f64("Nope", 1.0),
        Err(crate::SofaError::MissingVariable(_))
    ));
}

#[test]
fn attribute_on_undeclared_variable_is_missing_variable() {
    let mut writer = Hdf5Writer::new();
    assert!(
        writer
            .add_variable_attribute_str("Nope", "Units", "metre")
            .is_err()
    );
}

#[test]
fn unknown_dimension_is_missing_dimension() {
    let mut writer = Hdf5Writer::new();
    writer.add_dimension("M", 2);
    writer.add_variable_f32("X", &["Q"]);
    writer.write_f32("X", &[1.0, 2.0]).unwrap();
    assert!(matches!(
        writer.build(),
        Err(crate::SofaError::MissingDimension(_))
    ));
}

#[test]
fn large_root_object_header_round_trips() {
    // 300 link messages need ~6KB of root OH — beyond the old fixed 4096-byte
    // placeholder. The writer must size it exactly and stay readable.
    let mut writer = Hdf5Writer::new();
    for i in 0..300 {
        let name = format!("Var{i:03}");
        writer.add_variable_f32(&name, &[]);
        writer.write_scalar_f32(&name, i as f32).unwrap();
    }
    let bytes = writer.build().unwrap();
    let file = crate::Hdf5File::from_slice(&bytes).unwrap();
    assert_eq!(file.read_scalar_f32("Var000").unwrap(), 0.0);
    assert_eq!(file.read_scalar_f32("Var299").unwrap(), 299.0);
}
